### ISSUE TITLE
Replace INTO-CPS logo with one with a transparent background.

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/into-cps-app-documentation#4]
Currently, the logo looks like crap

![image](https://user-images.githubusercontent.com/18687499/74343510-753e8780-4dab-11ea-8b7f-293d2180f74f.png)

I have not been able to find one of reasonable resolution online, so maybe we have to make one.

**Comment by clegaard** [comment]
Replaced with svg provided by PGL

**Comment by CThuleHansen** [comment]
Hi clegaard, we actually have an open issue related to this on gitlab. 
We need new logos that combines into-cps, au, and digital twins
